<?php
use Drupal\Core\Template\Attribute;
use Drupal\Core\Link;

function dropsolid_dependency_injection_preprocess_breadcrumb(&$variables) {

  $node = \Drupal::routeMatch()->getParameter('node');
  $current_path = \Drupal::service('path.current')->getPath();

  // Override breadcrumbs to: Home > Dropsolid > Example > Photos
  if(!empty($current_path) && $current_path == '/dropsolid/example/photos') {
    $variables['breadcrumb'] = array();

    $request = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    $page_title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());

    $variables['breadcrumb'][] = [
      'text' => t("Home"),
      'url' => '/'
    ];

    $variables['breadcrumb'][] = [
      'text' => t("Dropsolid"),
      'url' => '/dropsolid'
    ];

    $variables['breadcrumb'][] = [
      'text' => t("Example"),
      'url' => '/dropsolid/example'
    ];

    $variables['breadcrumb'][] = [
      'text' => t("Photos"),
      'url' => '/dropsolid/example/photos',
      'attributes' => new Attribute(['class' => ['active']])
    ];
  }
}
